"""Deterministic rules engine modules."""

from pilgrim.rules.alms import (
    apply_alms_threshold_reward,
    clamp_alms_position,
    crossed_alms_thresholds,
    move_alms_position,
    resolve_alms_season_end,
    resolve_give_alms,
    score_alms_table,
)
from pilgrim.rules.buildings import (
    available_player_board_slots,
    building_by_id,
    building_donation_vp,
    building_names_for_ids,
    building_stone_cost,
    buildings_by_level,
    default_building_market,
    has_available_player_board_slot,
    load_building_config,
    used_player_board_slots,
    validate_building_catalogue,
    validate_building_market,
    validate_building_state,
    validate_player_board_slots,
)
from pilgrim.rules.dummy import (
    clockwise_duty_positions,
    move_dummy_acolytes_end_of_season,
    seed_dummy_acolytes,
    seed_dummy_groups,
    seed_from_anchor,
)
from pilgrim.rules.merchant import (
    advance_merchant_position,
    building_hire_payment_resource,
    current_merchant_duty,
    current_merchant_resource,
    merchant_position_name,
    trade_route_income_resource,
)
from pilgrim.rules.piety import clamp_piety, move_piety, score_piety
from pilgrim.rules.round_end import (
    apply_excess_resource_caps,
    resolve_trade_route_income,
    select_next_start_player,
)
from pilgrim.rules.ship import advance_ship_position, is_nw_pilgrimage_site, is_pilgrimage_site
from pilgrim.rules.special_activities import (
    all_special_activity_ids,
    allocate_abbey_to_city,
    allocate_abbey_to_special_activity,
    alms_house_extra_payment_options,
    available_special_activities,
    can_use_alms_house_bonus,
    clerical_devotion_bonus,
    clerical_silversmith_bonus,
    format_special_activities,
    has_special_activity,
    occupied_special_activities,
    produce_grain_bonus,
    produce_stone_bonus_hook,
    road_engineer_duty_value_bonus_hook,
    special_activity_count,
)
from pilgrim.rules.timing import (
    advance_active_player,
    advance_timing,
    is_round_end,
    is_season_end,
    resolve_round_end,
    resolve_season_end,
)
from pilgrim.rules.transition import TransitionResult, apply_action, legal_actions
from pilgrim.rules.validation import TransitionValidationError, validate_state_invariants

__all__ = [
    "apply_alms_threshold_reward",
    "clamp_alms_position",
    "crossed_alms_thresholds",
    "move_alms_position",
    "resolve_alms_season_end",
    "resolve_give_alms",
    "score_alms_table",
    "clockwise_duty_positions",
    "load_building_config",
    "building_by_id",
    "buildings_by_level",
    "validate_building_catalogue",
    "validate_building_market",
    "default_building_market",
    "building_stone_cost",
    "building_donation_vp",
    "used_player_board_slots",
    "available_player_board_slots",
    "has_available_player_board_slot",
    "validate_player_board_slots",
    "validate_building_state",
    "building_names_for_ids",
    "move_dummy_acolytes_end_of_season",
    "seed_dummy_acolytes",
    "seed_dummy_groups",
    "seed_from_anchor",
    "apply_excess_resource_caps",
    "resolve_trade_route_income",
    "select_next_start_player",
    "advance_ship_position",
    "is_nw_pilgrimage_site",
    "is_pilgrimage_site",
    "all_special_activity_ids",
    "allocate_abbey_to_city",
    "allocate_abbey_to_special_activity",
    "alms_house_extra_payment_options",
    "available_special_activities",
    "can_use_alms_house_bonus",
    "clerical_devotion_bonus",
    "clerical_silversmith_bonus",
    "format_special_activities",
    "has_special_activity",
    "occupied_special_activities",
    "produce_grain_bonus",
    "road_engineer_duty_value_bonus_hook",
    "produce_stone_bonus_hook",
    "special_activity_count",
    "advance_active_player",
    "advance_merchant_position",
    "advance_timing",
    "building_hire_payment_resource",
    "clamp_piety",
    "is_round_end",
    "is_season_end",
    "current_merchant_duty",
    "current_merchant_resource",
    "merchant_position_name",
    "move_piety",
    "resolve_round_end",
    "resolve_season_end",
    "score_piety",
    "trade_route_income_resource",
    "TransitionResult",
    "TransitionValidationError",
    "apply_action",
    "legal_actions",
    "validate_state_invariants",
]
