"""The ground the whole board sits on: a dark field, generated rather than drawn.

WHY THIS IS A SCRIPT AND NOT A PICTURE IN A FOLDER

Nothing here is traced, photographed or generated by a model. It is four octaves of seeded noise,
warmed towards the parchment's own hue and pulled down at the corners -- so it has no provenance
to carry, nothing to attribute and no licence to honour, which is not true of anything else in
`ui/assets-gothic`. Re-running this file with the same seed gives the same field byte for byte, so
the committed image is a convenience rather than the source of truth.

THE ONE NUMBER THAT MATTERS

The board is a lattice: 32% of the canvas is exposed ground, most of it in the channels between the
duty tiles, and the tiles are read by their torn silhouettes. Measured over a 5 px band just inside
every tile outline, that silhouette has a median luminance of 53.4 -- so wherever the ground rises
above that, the edge stops separating and the tile goes soft. It does not fail everywhere at once:
it fails in the region where the field happens to be bright, which reads as one corner of the board
being wrong rather than as a colour being wrong, and that is a much harder fault to name.

CEILING is that limit with room to spare. `--check` measures the finished field through the real
exposed-ground mask and refuses to write one that breaks it, because a field that looks right in
isolation and fails behind the tiles is exactly the mistake this file exists to prevent.
"""

import argparse
import pathlib

import numpy as np
from PIL import Image, ImageFilter

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "assets-gothic" / "ui" / "ground.webp"

W, H = 1600, 1200
SEED = 7
# Luminance the field must stay under where it shows. The tile silhouette's own median is 53.4;
# 50 keeps every edge separating with a little left over for a display that runs bright.
CEILING = 50.0
# Warmth. The parchment is #e7bd83, so the ground leans the same way rather than going blue --
# a cold grey next to warm panels reads as two different materials lit by two different lights.
TINT = (1.00, 0.93, 0.80)
OCTAVES = ((4, 1.0), (9, 0.5), (23, 0.25), (60, 0.12))


def field(w: int = W, h: int = H, seed: int = SEED, gain: float = 0.21,
          floor: float = 0.06, vignette: float = 0.55) -> Image.Image:
    """Four octaves of value noise, warmed and vignetted. Deterministic in `seed`."""
    rng = np.random.default_rng(seed)
    f = np.zeros((h, w))
    for cells, amp in OCTAVES:
        n = rng.random((cells, max(2, int(cells * w / h))))
        up = Image.fromarray((n * 255).astype(np.uint8)).resize((w, h), Image.BICUBIC)
        f += amp * np.asarray(up) / 255
    f = (f - f.min()) / (f.max() - f.min())
    yy, xx = np.mgrid[0:h, 0:w]
    vig = 1 - vignette * (((xx - w / 2) / (w / 2)) ** 2 + ((yy - h / 2) / (h / 2)) ** 2) / 2
    lum = np.clip(f * gain + floor, 0, 1) * np.clip(vig, 0, 1)
    rgb = np.stack([lum * TINT[0], lum * TINT[1], lum * TINT[2]], -1)
    return Image.fromarray((rgb * 255).astype(np.uint8)).filter(
        ImageFilter.GaussianBlur(1.2 * w / W))


def luminance(im: Image.Image) -> np.ndarray:
    a = np.asarray(im.convert("RGB")).astype(float)
    return 0.2126 * a[:, :, 0] + 0.7152 * a[:, :, 1] + 0.0722 * a[:, :, 2]


def under_ceiling(im: Image.Image, ceiling: float = CEILING,
                  mask: np.ndarray | None = None) -> tuple[float, float, bool]:
    """The field's brightness WHERE IT SHOWS, not over the whole picture.

    Without the mask the panels drag the average down and a field that is far too bright in the
    gutters still passes -- the covered 68% is the part that cannot possibly matter.
    """
    lum = luminance(im)
    vals = lum[mask] if mask is not None else lum.ravel()
    return float(np.median(vals)), float(np.percentile(vals, 99)), bool(np.percentile(vals, 99) <= ceiling)


def exposed_mask(template: pathlib.Path, size: tuple[int, int]) -> np.ndarray | None:
    """Which pixels the ground actually shows through, from a knocked-out board render."""
    if not template.is_file():
        return None
    tpl = Image.open(template).convert("RGBA").resize(size, Image.NEAREST)
    return np.asarray(tpl)[:, :, 3] < 8


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=pathlib.Path, default=OUT)
    ap.add_argument("--scale", type=int, default=2,
                    help="multiple of the 1600x1200 canvas to render at (default %(default)s); "
                         "the stage is CSS-scaled, so 1x softens on a display wider than 1600")
    ap.add_argument("--seed", type=int, default=SEED)
    ap.add_argument("--gain", type=float, default=0.21, help="contrast of the noise; 0.30 looked "
                         "right in isolation and broke the ceiling behind the tiles")
    ap.add_argument("--quality", type=int, default=88)
    ap.add_argument("--check", type=pathlib.Path, default=None,
                    help="a knocked-out board PNG; measures the field through the real exposed "
                         "ground and refuses to write one that breaks the ceiling")
    z = ap.parse_args()

    w, h = W * z.scale, H * z.scale
    im = field(w, h, seed=z.seed, gain=z.gain)
    mask = exposed_mask(z.check, (w, h)) if z.check else None
    med, p99, ok = under_ceiling(im, mask=mask)
    where = "through the exposed ground" if mask is not None else "over the whole field"
    print("%dx%d  median L %.1f, 99th pct %.1f  (%s, ceiling %.0f)"
          % (w, h, med, p99, where, CEILING))
    if not ok:
        raise SystemExit(
            "the field reaches L %.1f where it shows, over the %.0f ceiling -- the tile edges "
            "would stop separating there. Lower --gain and run it again." % (p99, CEILING))
    z.out.parent.mkdir(parents=True, exist_ok=True)
    im.save(z.out, "WEBP", quality=z.quality, method=6)
    print("written %s  %.2f MB" % (z.out, z.out.stat().st_size / 1e6))
